name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        with:
          target: ${{ matrix.target }}
          run: cargo build --verbose && cargo test --verbose
          sccache: 'true'
          manylinux: auto

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64, x86]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        with:
          target: ${{ matrix.target }}
          run: cargo build --verbose && cargo test --verbose
          sccache: 'true'

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        with:
          target: ${{ matrix.target }}
          run: cargo build --verbose && cargo test --verbose
          sccache: 'true'
